/** Registro central de imagens (require estático exigido pelo Metro). */
export const images = {
  assistircanaisicon: require('../../assets/images/modules_img_assistircanaisicon.png'),
  baixaraplicativoicon: require('../../assets/images/modules_img_baixaraplicativoicon.png'),
  baixarnuvensmfcicon: require('../../assets/images/modules_img_baixarnuvensmfcicon.png'),
  bandeirasPaisesBrasil: require('../../assets/images/modules_img_bandeiras_paises_brasil.png'),
  cardsAmex: require('../../assets/images/modules_img_cards_amex.png'),
  cardsDiners: require('../../assets/images/modules_img_cards_diners.png'),
  cardsDiscover: require('../../assets/images/modules_img_cards_discover.png'),
  cardsElo: require('../../assets/images/modules_img_cards_elo.png'),
  cardsHipercard: require('../../assets/images/modules_img_cards_hipercard.png'),
  cardsJcb: require('../../assets/images/modules_img_cards_jcb.png'),
  cardsMastercard: require('../../assets/images/modules_img_cards_mastercard.png'),
  cardsVisa: require('../../assets/images/modules_img_cards_visa.png'),
  comprarrecarga: require('../../assets/images/modules_img_comprarrecarga.png'),
  comprarrecargamfc: require('../../assets/images/modules_img_comprarrecargamfc.png'),
  comprarrecargatve: require('../../assets/images/modules_img_comprarrecargatve.png'),
  comprarrecargatvemfc: require('../../assets/images/modules_img_comprarrecargatvemfc.png'),
  iconFilmes: require('../../assets/images/modules_img_icon_filmes.png'),
  logoHeader: require('../../assets/images/modules_img_logo_header.png'),
  logolarge: require('../../assets/images/modules_img_logolarge.png'),
  logomfc: require('../../assets/images/modules_img_logomfc.png'),
  logotve: require('../../assets/images/modules_img_logotve.png'),
  mfc: require('../../assets/images/modules_img_mfc.png'),
  novousuarioicon: require('../../assets/images/modules_img_novousuarioicon.png'),
  recuperarsenha: require('../../assets/images/modules_img_recuperarsenha.png'),
  suporte: require('../../assets/images/modules_img_suporte.png'),
  suporteFacebook: require('../../assets/images/modules_img_suporte_facebook.png'),
  suporteTelegram: require('../../assets/images/modules_img_suporte_telegram.png'),
  suporteWhatsapp: require('../../assets/images/modules_img_suporte_whatsapp.png'),
  tve: require('../../assets/images/modules_img_tve.png'),
  tvemarcadagua: require('../../assets/images/modules_img_tvemarcadagua.png'),
} as const;
